---
development:
  cloud_name: hicnvkyte
  api_key: '369411872814749'
  api_secret: "-Ue7q5yDIz52-MRxeBwwAS5_pXo"
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: hicnvkyte
  api_key: '369411872814749'
  api_secret: "-Ue7q5yDIz52-MRxeBwwAS5_pXo"
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: hicnvkyte
  api_key: '369411872814749'
  api_secret: "-Ue7q5yDIz52-MRxeBwwAS5_pXo"
  enhance_image_tag: true
  static_image_support: false
